### ISSUE TITLE
Getting different autofocus values after propagating

### ISSUE THREAD

**Issue by PinkShnack** [RI-imaging/nrefocus#13]
### What I am doing:
I am loading a hologram, and getting the field from `qpimage.QPImage`. Then I refocus with `nrefocus.RefocusNumpy` and use `nrefocus.RefocusNumpy.autofocus` to get the optimum focus.
Then I propagate the `field` by a given value.  I repeat the refocus and autofocus as above, but this time use the propagation value as the initial `distance` for `nrefocus.RefocusNumpy`. 

[See the script here](https://gist.github.com/PinkShnack/eff6328efe06f7a7bf1bce92b43f722f) for this file: [hologram_cell_curved_bg](https://user-images.githubusercontent.com/43960046/122543313-efc88880-d02b-11eb-9b15-adc9de7587ed.jpg)

I crop the image, but it happens regardless of cropping.
I also am reloading the saved propagated field with `qpimage.QPImage`, but this isn't the cause of the issue.

### Expected behaviour
The focuses from both fields should be the same. (Is this expected?)

### Actual behaviour
The focuses deviate by about 2-3 microns in this case. See the below images. First and second image are the first and second calculation of the minimizer.

Probably something to do with the noise near 0 that exists in the second, propagated field.

![Optimum focus 33 09 um](https://user-images.githubusercontent.com/43960046/122542554-1d610200-d02b-11eb-81bb-73c0e0179075.png)
![Optimum focus 30 60 um](https://user-images.githubusercontent.com/43960046/122542563-1fc35c00-d02b-11eb-8d82-251dc786babf.png)

**Comment by paulmueller** [comment]
There are two issues with this hologram:

1. It is horribly out of focus (30µm)
2. There is a lot of noise in the amplitude data, the data which is used in the metric computation.

Other than that, you could maybe perform background correction by default.

The issue is that when you propagate, there is always some information lost when you use `padding=True` (which is the default, because it reduces ringing artifacts). To illustrate this, have a look at this modified script and execute it with `PADDING` set to True and False:

```
import cv2
import nrefocus
import qpimage
import matplotlib.pyplot as plt
import numpy as np

PADDING = False

# open and crop hologram image
holo_im = "hologram_cell_curved_bg.jpg"

img = cv2.imread(str(holo_im), cv2.IMREAD_GRAYSCALE)
img_crop = img[200:600, 0:400]

qpi = qpimage.QPImage(data=img_crop, which_data="hologram")
qpi.compute_bg(which_data=["phase", "amplitude"],
               fit_offset="fit",
               fit_profile="poly2o",
               border_px=30,
               )

field0 = qpi.field

# example nrefocus parameters
focus_range = (-50e-6, 50e-6)
pixel_size = 0.34e-6
light_wavelength = 532e-9

afocus1 = nrefocus.RefocusPyFFTW(
    field0, light_wavelength, pixel_size, padding=PADDING)
af1, (grid1, metric1), field1 = afocus1.autofocus(focus_range,
                                                  ret_field=True,
                                                  ret_grid=True)
print(af1*1e6)


afocus2 = nrefocus.RefocusPyFFTW(
    afocus1.propagate(30e-6), light_wavelength, pixel_size, padding=PADDING)
af2, (grid2, metric2), field2 = afocus2.autofocus(focus_range,
                                                  ret_field=True,
                                                  ret_grid=True)
print(af2*1e6)

print((af2 - af1)*1e6)

plt.subplot(3, 2, 1, title="af grid 1")
plt.plot(grid1*1e6, metric1)

plt.subplot(3, 2, 2, title="af grid 2")
plt.plot(grid2*1e6, metric2)

# plot both images
plt.subplot(323, title=f"phase 1")
plt.imshow(np.angle(field1))


plt.subplot(324, title=f"phase 2")
plt.imshow(np.angle(field2))


plt.subplot(325, title="amp 1")
plt.imshow(np.abs(field1), cmap="gray")

plt.subplot(326, title="amp 2")
plt.imshow(np.abs(field2), cmap="gray")


plt.tight_layout()
plt.savefig("without_padding.png")
plt.show()
```
![without_padding](https://user-images.githubusercontent.com/2853022/122569547-25309e80-d04b-11eb-824f-81af39005756.png)
![with_padding](https://user-images.githubusercontent.com/2853022/122569552-25c93500-d04b-11eb-9d78-b76b2374bd93.png)

**Comment by PinkShnack** [comment]
This is great thanks for the detailed reply. Much clearer now. I will close this issue, but I could add this script as an example in `nrefocus`?
