### ISSUE TITLE
Scale affects minimizer convergence

### ISSUE THREAD

**Issue by paulmueller** [RI-imaging/nrefocus#14]
If I set things in [m] instead of [µm ], then the minimizer behaves differently. This can be fixed by converting the minimization interval to pixels (using pixel size) instead of leaving the original interval in SI units.

@PinkShnack

**Comment by PinkShnack** [comment]
Thanks. So for example an interval of -5 to 5 microns (-5e-6, 5e-6) should be (in our case): (-5e-60.34, 5e-6*0.34)?

FYI on github my tag is @PinkShnack :D

**Comment by paulmueller** [comment]
Sorry, not used anymore to working with you here.

Yes, so nrefocus should internally convert from [m] to [px] before passing the interval to the minimizer. In our case (-5e-6/0.34e-6, 5e-6/0.34e-6).

There is nothing you can do right now as a user.

**Comment by PinkShnack** [comment]
So do you mean that this needs to be changed in the codebase? I can't just do this now in a script and make it work?

**Comment by paulmueller** [comment]
correct

**Comment by PinkShnack** [comment]
Great, are you planning to fix it? I can create a pull request!

**Comment by paulmueller** [comment]
A PR would be great! I have a few other more urgent things, so I would probably not be able to take a look this week.

**Comment by paulmueller** [comment]
It turned out that the normalization can be done locally in the lmfit minimizer and did not have to be done globally. Since it only affected the lmfit minimizer, this is fine.

Also, I normalized by wavelength instead of pixel size. This should be fine.

If you still encounter this issue, please add an example script.
