### ISSUE TITLE
problem with using autofocus function

### ISSUE THREAD

**Issue by XiaHua-Spark** [RI-imaging/nrefocus#3]
how to set the ival?

my pix size is 0.835um, distance is around 710um.
the distance in pix is 710/0.835 = 850.
so I choose ival to be (845.0,855.0).

but the program runs for a very long time and does not stop.
am I setting the wrong ival?

here is my code:
```
ival= (845. , 855.)
field = nrefocus.autofocus(im, 1.5, 0.66, depth_range) 
# 1.5 is the Refractive index
# 0.66 is the wavelength in pix: (0.55um/0.835um)
```

**Comment by paulmueller** [comment]
I have never worked with such large focusing distances. My guess is that at these distances (almost 3 orders of magnitude larger than the wavelength), there is not much information left. You would need a very large field of view and good sampling. It could also be a problem with the autofocusing implementation.

You could try to perform manual refocusing using [nrefocus.refocus](http://ri-imaging.github.io/nrefocus/#refocus-individual-fields) to check if refocusing makes sense in your case.

**Comment by paulmueller** [comment]
You could also try `ival= (-855. , -845.)`.
